apiVersion: v1
kind: Pod
metadata:
  name: my-postgres-db
  labels:
    app: postgres
spec:
  securityContext:
    fsGroup: 999

  initContainers:
    - name: wipe-data
      image: busybox
      command: ["sh", "-c"]
      args:
        - |
          echo "Cleaning data directory...";
          rm -rf /var/lib/postgresql/data/*;
          chown -R 999:999 /var/lib/postgresql/data;
          chmod 700 /var/lib/postgresql/data;
      volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data

  containers:
    - name: postgres
      image: husseinsahm/lib-postgres-db:latest
      ports:
        - containerPort: 5432
      env:
        - name: POSTGRES_DB
          value: librarydb
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: postgres123
      volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data

  volumes:
    - name: postgres-storage
      persistentVolumeClaim:
        claimName: postgres-pvc
