apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  clusterIP: None
  ports:
  - port: 5432
  selector:
    app: postgres

------ 1111----

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
spec:
  serviceName: "postgres-service"
  replicas: 1
  selector:
    matchLabels:
      app: postgres

  template:
    metadata:
      labels:
        app: postgres
    spec:
      securityContext:
        fsGroup: 999   # postgres user group

      initContainers:
      - name: init-db
        image: busybox
        command: ["sh", "-c"]
        args:
          - |
            echo "[INIT] Fixing permissions and cleaning directory...";
            rm -rf /var/lib/postgresql/data/*;
            mkdir -p /var/lib/postgresql/data;
            chmod 700 /var/lib/postgresql/data;
            chown -R 999:999 /var/lib/postgresql/data;
        securityContext:
          runAsUser: 0      # ← ROOT FIX!!!
          runAsGroup: 0
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data

      containers:
      - name: postgres
        image: postgres:15
        env:
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: postgres123
        - name: POSTGRES_DB
          value: librarydb
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data

  volumeClaimTemplates:
  - metadata:
      name: postgres-storage
      labels:
        app: postgres
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 1Gi
      storageClassName: gp2
