apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  clusterIP: None  # Headless service عشان StatefulSet
  selector:
    app: postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  serviceName: postgres
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      # هنا الـ initContainer اللي كنت مستخدمه قبل كده
      initContainers:
        - name: init-db
          image: busybox
          command: ["sh", "-c"]
          args:
            - |
              echo "[INIT] Fixing permissions and cleaning directory...";
              rm -rf /var/lib/postgresql/data/*;
              mkdir -p /var/lib/postgresql/data;
              chmod 700 /var/lib/postgresql/data;
              chown -R 999:999 /var/lib/postgresql/data;
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
      containers:
        - name: postgres
          image: postgres:15
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
              name: postgres
          env:
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "postgres123"
            - name: POSTGRES_DB
              value: "librarydb"
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
          # Probes محترمة عشان الـ readiness / liveness
          readinessProbe:
            tcpSocket:
              port: 5432
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 5432
            initialDelaySeconds: 30
            periodSeconds: 20
      # ممكن تحط tolerations / nodeSelector لو حابب بعدين
  volumeClaimTemplates:
    - metadata:
        name: postgres-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: gp2   # مهم جداً: نستخدم StorageClass الافتراضي اللي عندك
        resources:
          requests:
            storage: 5Gi
